# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20161124_0333'),
        ('subscriptions', '0003_auto_20161124_0358'),
    ]

    operations = [
    ]
